config/routes.rb
Rails.application.routes.draw do

  resources :posts

  devise_for :users
  root to: 'pages#home'

  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
    @post = Post.last
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    if current_user.admin
      @post = Post.new
    else
      redirect_to root_path
    end
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:titulo, :content, :author, :publish, :photoguy,:content2, :content3, :content4, :content5, :photo, :photo_cache)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <link href="https://fonts.googleapis.com/css?family=Gruppo|VT323" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body class="Site">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <main class="Site-content">
    <%= yield %>
    </main>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="expocicion" style="background-image: url('<%= cl_image_path @post.photo%>');background-position: center;-webkit-filter: grayscale(100%); filter: grayscale(100%);">
    <div class= "padded">
      <h2>Tendencia: </h2> <br>
      <h1><%=@post.titulo%></h1>
      <br>
      <h6 class="btn btn-primary">Ver más</h6>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="row">
   <% @posts.reverse_each do |post| %>
   <%= link_to post_path(post) do %>
   <hr>
   <div class="card">
     <%= cl_image_tag post.photo, height: 300, width: 400, crop: :fill %>
     <div style="padding-left: 10px;">
      <h2><%= post.titulo %></h2>
      <p>By: <%= post.author %> | <%= post.publish %></p>
    </div>
  </div>
  <%end%>
  <% end %>
</div>
</div>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
  <div class="padded">
    <div class="container">
      <%= simple_form_for @post do |f| %>
      <%= f.input :titulo %>
      <%= f.input :content %>
      <%= f.input :content2 %>
      <%= f.input :content3 %>
      <%= f.input :content4 %>
      <%= f.input :content5 %>
      <%= f.input :author %>
      <%= f.input :publish %>
      <%= f.input :photoguy %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit%>
      <% end %>
    </div>
  </div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h2><%= post.titulo %></h2>
<% end %>

app/views/posts/new.html.erb
<div class="padded">
  <div class="container">
  <%= simple_form_for @post do |f| %>
  <%= f.input :titulo %>
  <%= f.input :content %>
  <%= f.input :content2 %>
  <%= f.input :content3 %>
  <%= f.input :content4 %>
  <%= f.input :content5 %>
  <%= f.input :author %>
  <%= f.input :publish %>
  <%= f.input :photoguy %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>s
  <%= f.submit%>
  <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="container">
    <div class="expocicion" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path @post.photo, height: 300, width: 400, crop: :fill %>')">
      <div class= "padded">
        <h1><%=@post.titulo%></h1>
        <br>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="padded content">
          <p><%=@post.content%></p>
          <br>
          <p><%=@post.content2%></p>
          <br>
          <p><%=@post.content3%></p>
          <br>
          <p><%=@post.content4%></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li><a href="https://www.instagram.com/panama.instantanea/"><i class="fa fa-instagram"></i></a></li>
          <li><a href="https://www.facebook.com/PIPCultural/"><i class="fa fa-facebook"></i></a></li>
          <li><a href="https://twitter.com/PuntoBohemio"><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right footer-logo">
        <%= image_tag('logo.png')%>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <h3>www.trendingspanama.com</h3>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" style="color: white;" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
           <%= link_to "New Post", new_post_path, class: "navbar-wagon-item navbar-wagon-link" %>
         </li>
         <li>
          <%= link_to "#" do %>
          <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <%end %>
</div>
<%#else %>
<!-- Login link (when logged out) -->
<%#=link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%#end %>

<!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><a href="#">Some mobile link</a></li>
      <li><a href="#">Other one</a></li>
      <li><a href="#">Other one</a></li>
    </ul>
  </div>
</div>
</div>